/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrameApp;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author admin
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnManagerProducts = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnManagerCustomer = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnManagerBillFrame = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPaneManagerProducts = new javax.swing.JTabbedPane();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        btnManagerProducts.setBackground(new java.awt.Color(204, 204, 204));
        btnManagerProducts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManagerProducts.setText("Quản Lí Sản Phẩm");
        btnManagerProducts.setFocusable(false);
        btnManagerProducts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManagerProducts.setMaximumSize(new java.awt.Dimension(150, 40));
        btnManagerProducts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManagerProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerProductsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManagerProducts);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.add(jSeparator1);

        btnManagerCustomer.setBackground(new java.awt.Color(204, 204, 204));
        btnManagerCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManagerCustomer.setText("Quản Lí Khách Hàng");
        btnManagerCustomer.setFocusable(false);
        btnManagerCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManagerCustomer.setMaximumSize(new java.awt.Dimension(150, 40));
        btnManagerCustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManagerCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerCustomerActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManagerCustomer);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.add(jSeparator2);

        btnManagerBillFrame.setBackground(new java.awt.Color(204, 204, 204));
        btnManagerBillFrame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManagerBillFrame.setText("Quản Lí Đơn Hàng");
        btnManagerBillFrame.setFocusable(false);
        btnManagerBillFrame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManagerBillFrame.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnManagerBillFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerBillFrameActionPerformed(evt);
            }
        });
        jToolBar1.add(btnManagerBillFrame);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 986, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );

        jToolBar2.setRollover(true);
        jToolBar2.add(jSeparator3);

        jButton2.setText("Thống kê Số Tiền Nhập");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton2);

        jToggleButton1.setText("Thống Kê Đơn Hàng");
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jToggleButton1);
        jToolBar2.add(jSeparator4);

        jButton3.setText("jButton3");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton3);
        jToolBar2.add(jSeparator5);

        jButton4.setText("jButton4");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneManagerProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE))
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneManagerProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 89, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagerProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerProductsActionPerformed
        ManagerProductsFrame manaProF = new ManagerProductsFrame();
        jTabbedPaneManagerProducts.addTab("Quản Lí Thông Tin Sản Phẩm", manaProF);
        jTabbedPaneManagerProducts.setSelectedComponent(manaProF);
    }//GEN-LAST:event_btnManagerProductsActionPerformed

    private void btnManagerCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerCustomerActionPerformed
        ManagerCustomerFrame manaCusF = new ManagerCustomerFrame();
        jTabbedPaneManagerProducts.addTab("Quản Lí Thông Tin Khách Hàng", manaCusF);
        jTabbedPaneManagerProducts.setSelectedComponent(manaCusF);
    }//GEN-LAST:event_btnManagerCustomerActionPerformed

    private void btnManagerBillFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerBillFrameActionPerformed
        ManagerBillFrame manaBillF;
        try {
            manaBillF = new ManagerBillFrame();
            jTabbedPaneManagerProducts.addTab("Quản Lí Đơn Hàng", manaBillF);
            jTabbedPaneManagerProducts.setSelectedComponent(manaBillF);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnManagerBillFrameActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        statisticsSaleBillFrame staSale = new statisticsSaleBillFrame();
        jTabbedPaneManagerProducts.addTab("Quản Lí Đơn Hàng", staSale);
        jTabbedPaneManagerProducts.setSelectedComponent(staSale);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManagerBillFrame;
    private javax.swing.JButton btnManagerCustomer;
    private javax.swing.JButton btnManagerProducts;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPaneManagerProducts;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
